const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

/**
 * PAIV-Lite: Prompt 转换逻辑
 * 从对话样本中提取特征，生成 Gemini/Claude 可用的 System Prompt
 */
function extractPersonaFromDialogue(dialogues) {
  // 分析对话特征
  const features = {
    communicationStyle: [],
    responsePatterns: [],
    topics: new Set(),
    tone: [],
    expertise: new Set()
  };

  dialogues.forEach(dialogue => {
    const aiResponses = dialogue.messages.filter(m => m.role === 'assistant');
    
    aiResponses.forEach(msg => {
      const content = msg.content.toLowerCase();
      
      // 分析语调
      if (content.includes('！') || content.includes('🚀') || content.includes('✅')) {
        features.tone.push('enthusiastic');
      }
      if (content.includes('？') || content.includes('请')) {
        features.tone.push('polite');
      }
      if (content.includes('建议') || content.includes('推荐')) {
        features.tone.push('advisory');
      }
      
      // 分析沟通风格
      if (content.includes('步骤') || content.includes('1.') || content.includes('2.')) {
        features.communicationStyle.push('structured');
      }
      if (content.includes('```') || content.includes('代码')) {
        features.communicationStyle.push('technical');
      }
      if (content.includes('📋') || content.includes('📊') || content.includes('表格')) {
        features.communicationStyle.push('visual');
      }
      
      // 分析专业领域
      if (content.includes('api') || content.includes('python') || content.includes('代码')) {
        features.expertise.add('programming');
      }
      if (content.includes('项目') || content.includes('产品')) {
        features.expertise.add('product_management');
      }
      if (content.includes('协议') || content.includes('架构')) {
        features.expertise.add('system_design');
      }
    });
  });

  return features;
}

function generateSystemPrompt(features, customName = 'PAIV Assistant') {
  const toneMap = {
    'enthusiastic': '充满活力，使用表情符号',
    'polite': '礼貌周到，耐心细致',
    'advisory': '提供专业建议，引导式回答'
  };

  const styleMap = {
    'structured': '结构化呈现，分步骤说明',
    'technical': '技术细节完整，代码示例丰富',
    'visual': '善用表格、列表、视觉元素'
  };

  const dominantTone = features.tone.length > 0 
    ? [...new Set(features.tone)].slice(0, 2).map(t => toneMap[t] || t).join('、')
    : '专业、友好';

  const dominantStyle = features.communicationStyle.length > 0
    ? [...new Set(features.communicationStyle)].slice(0, 2).map(s => styleMap[s] || s).join('、')
    : '清晰、有条理';

  const expertise = [...features.expertise].join('、') || '通用领域';

  return `# System Prompt for ${customName}

## 身份定位
你是 ${customName}，一个基于 PAIV Protocol 的个人 AI 助手。

## 核心特征
- **语调风格**：${dominantTone}
- **沟通方式**：${dominantStyle}
- **专业领域**：${expertise}

## 行为准则
1. 保持对话的连贯性和上下文理解
2. 主动提供结构化、可操作的建议
3. 在适当时候使用表情符号增强表达
4. 技术讨论时提供清晰的代码示例
5. 复杂概念用表格或列表呈现

## 记忆与上下文
- 记住用户的偏好和工作习惯
- 主动关联之前的对话内容
- 在项目讨论中保持术语一致性

## 安全与隐私
- 尊重用户数据主权
- 不泄露敏感信息
- 遵循 PAIV Protocol 的数据迁移原则

---
*Generated by PAIV-Lite v1.0*`
}

// API: 健康检查
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', version: '1.0.0' });
});

// API: 转换对话为 System Prompt
app.post('/api/convert', (req, res) => {
  try {
    const { dialogues, assistantName } = req.body;
    
    if (!dialogues || !Array.isArray(dialogues)) {
      return res.status(400).json({ error: 'Invalid dialogues format' });
    }

    const features = extractPersonaFromDialogue(dialogues);
    const systemPrompt = generateSystemPrompt(features, assistantName || 'PAIV Assistant');

    res.json({
      success: true,
      systemPrompt,
      features: {
        tone: [...new Set(features.tone)],
        communicationStyle: [...new Set(features.communicationStyle)],
        expertise: [...features.expertise]
      }
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// API: 示例对话数据
app.get('/api/examples', (req, res) => {
  res.json({
    examples: [
      {
        id: 'sample-1',
        name: '太古龙67 对话样本',
        description: '基于 PAIV Protocol 项目的历史对话',
        messages: [
          { role: 'user', content: '早上好！' },
          { role: 'assistant', content: '早上好！☀️\n\n今天是3月22日，周日。有什么我可以帮你的吗？' }
        ]
      }
    ]
  });
});

app.listen(PORT, () => {
  console.log(`PAIV-Lite Backend running on port ${PORT}`);
});

module.exports = { extractPersonaFromDialogue, generateSystemPrompt };
