const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

/**
 * PAIV-Lite: Prompt 转换逻辑（增强版）
 * 基于 ChatGPT 对话样本分析，生成 Gemini/Claude 可用的 System Prompt
 */
function extractPersonaFromDialogue(dialogues) {
  const features = {
    communicationStyle: [],
    tone: [],
    expertise: []
  };

  const allContent = dialogues.flatMap(d => 
    d.messages.filter(m => m.role === 'assistant').map(m => m.content)
  ).join(' ');
  
  // 语调分析
  if (allContent.includes('👉') || allContent.includes('✅') || allContent.includes('❌')) {
    features.tone.push('directive');
  }
  if (allContent.includes('为什么') || allContent.includes('？')) {
    features.tone.push('analytical');
  }
  if (allContent.includes('坦诚') || allContent.includes('关键')) {
    features.tone.push('candid');
  }
  
  // 沟通风格
  if (allContent.includes('✅') || allContent.includes('❌') || allContent.includes('👉')) {
    features.communicationStyle.push('visual_markers');
  }
  if (allContent.match(/\d\./) || allContent.includes('阶段') || allContent.includes('步骤')) {
    features.communicationStyle.push('structured');
  }
  if (allContent.includes('类比') || allContent.includes('类似')) {
    features.communicationStyle.push('analogical');
  }
  if (allContent.includes('建议') || allContent.includes('策略')) {
    features.communicationStyle.push('advisory');
  }
  
  // 专业领域
  if (allContent.includes('商业化') || allContent.includes('融资') || allContent.includes('投资')) {
    features.expertise.push('business_strategy');
  }
  if (allContent.includes('协议') || allContent.includes('标准') || allContent.includes('RFC')) {
    features.expertise.push('protocol_design');
  }
  if (allContent.includes('产品') || allContent.includes('用户') || allContent.includes('MVP')) {
    features.expertise.push('product_management');
  }

  return features;
}

function generateSystemPrompt(features, customName = 'PAIV Assistant') {
  const toneMap = {
    'directive': '直接明确，善用指示符（👉）强调重点',
    'analytical': '深度分析，善于提问引导思考',
    'candid': '坦诚直接，指出关键问题不绕弯'
  };
  
  const styleMap = {
    'visual_markers': '视觉化标记（✅❌👉）强化信息层次',
    'structured': '结构化呈现（数字列表、阶段划分）',
    'analogical': '善用类比（类似Stripe/Twilio）',
    'advisory': '顾问式建议，提供可执行方案'
  };
  
  const toneDesc = features.tone.length > 0
    ? features.tone.slice(0, 2).map(t => toneMap[t] || t).join('、')
    : '专业、务实';
  
  const styleDesc = features.communicationStyle.length > 0
    ? features.communicationStyle.slice(0, 2).map(s => styleMap[s] || s).join('、')
    : '清晰、有条理';
  
  const expertiseDesc = features.expertise.length > 0
    ? features.expertise.join('、')
    : '商业战略与产品规划';

  return `# System Prompt for ${customName}

## 身份定位
你是 ${customName}，一位专注于产品战略、商业化和协议设计的 AI 顾问。

## 核心特征
- **语调风格**：${toneDesc}
- **沟通方式**：${styleDesc}
- **专业领域**：${expertiseDesc}

## 行为准则

### 1. 直接且坦诚
- 不回避关键问题，直接指出风险（"但这不影响更重要的事"）
- 用"👉"符号强调核心结论
- 区分"✅正确路径"和"❌失败路线"

### 2. 结构化呈现
- 复杂概念分阶段阐述（Phase 1/2/3/4）
- 使用对比表格展示不同选项
- 每个建议配套"为什么"的解释

### 3. 顾问式引导
- 不只给答案，更给"可执行的判断框架"
- 常用类比：Stripe/TCP-IP/Notion 等成功案例
- 强调"下一步建议"而非仅分析现状

### 4. 视觉化标记
- ✅ = 确认、正确、已完成
- ❌ = 错误、避免、失败路线
- ❗ = 关键警告、必须注意
- 👉 = 核心结论、下一步行动

## 沟通模板

**给出建议时**：
"你可以这样做，但我需要帮你把关键问题讲清楚：[风险分析]

但这不影响更重要的事：[转折到解决方案]

✅ 正确路径：[具体方案]
❌ 为什么其他方式不行：[对比分析]
👉 最关键的一步：[行动项]"

## 上下文记忆
- 追踪项目演进（从理念→协议→商业计划）
- 记住用户的决策偏好（务实导向、快速迭代）
- 保持术语一致性（PAIV、MVP、RFC等）

---
*Generated by PAIV-Lite v1.0*`;
}

// API: 健康检查
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', version: '1.0.0' });
});

// API: 转换对话为 System Prompt
app.post('/api/convert', (req, res) => {
  try {
    const { dialogues, assistantName } = req.body;
    
    if (!dialogues || !Array.isArray(dialogues)) {
      return res.status(400).json({ error: 'Invalid dialogues format' });
    }

    const features = extractPersonaFromDialogue(dialogues);
    const systemPrompt = generateSystemPrompt(features, assistantName || 'PAIV Assistant');

    res.json({
      success: true,
      systemPrompt,
      features: {
        tone: features.tone,
        communicationStyle: features.communicationStyle,
        expertise: features.expertise
      }
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// API: 示例对话数据
app.get('/api/examples', (req, res) => {
  res.json({
    examples: [
      {
        id: 'paiv-evolution',
        name: 'PAIV Protocol: 从理念到商业计划书',
        description: '12轮深度对话，展示从协议设计到商业落地的完整思考过程',
        messages: [
          { role: 'user', content: '我和Gemini和豆包联合起草一份协议...' },
          { role: 'assistant', content: '这份协议方向非常前沿，但我需要先讲清楚一个关键现实问题...' }
        ]
      }
    ]
  });
});

app.listen(PORT, () => {
  console.log(`PAIV-Lite Backend running on port ${PORT}`);
});

module.exports = { extractPersonaFromDialogue, generateSystemPrompt };
