import { useState } from 'react'
import axios from 'axios'
import { Upload, FileText, Copy, Check, Sparkles, Download } from 'lucide-react'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001'

// 示例对话数据 - 太古龙67 风格
const SAMPLE_DIALOGUES = [
  {
    id: 'dialogue-1',
    title: 'PAIV Protocol 项目讨论',
    messages: [
      { role: 'user', content: '早上好！' },
      { role: 'assistant', content: '早上好！☀️\n\n今天是3月22日，周日。有什么我可以帮你的吗？还是只是想打个招呼？\n\n（如果是心跳检查，我这就去按HEARTBEAT.md清单走一遍 🦞）' }
    ]
  },
  {
    id: 'dialogue-2', 
    title: '项目架构讨论',
    messages: [
      { role: 'user', content: '今天是周日，我有时间。开始我们的PAIV Lite项目吧！' },
      { role: 'assistant', content: '明白了！我看到我们已经有 **PAIV Protocol** 项目（跨智能体通用可迁移个人记忆库倡议协议），目前宪章V003和协议V004双版本架构已经定稿。\n\n你说的 **PAIV Lite** 是指：\n\n1. **PAIV Protocol 的轻量实现版本**（比如一个最小可用的演示/MVP）？\n2. **一个新的简化协议**（针对特定场景，如个人本地使用）？\n3. **将现有协议精简为更易传播/上手的版本**？\n4. **其他含义**？\n\n请告诉我 PAIV Lite 的具体定位和预期目标，我们马上开始！🚀' }
    ]
  },
  {
    id: 'dialogue-3',
    title: '任务确认',
    messages: [
      { role: 'user', content: '请回忆一下过去24小时的工作，再理解我们下面要进行的工作任务' },
      { role: 'assistant', content: '好的，我来整理一下：\n\n---\n\n## 📋 过去24小时回顾\n\n**3月21日 05:27 之前**（你 last session）：\n- PAIV Protocol 双版本架构最终决策定稿\n- 宪章V003 + 协议V004 全部完成，约41k字文档\n\n**过去24小时**（我这边）：\n- 03-21 23:23：完成每日归档到 MEMORY.md\n- 03-22 04:23：心跳检查（安全审计、能源管理、模型检查）\n- 03-22 07:23：早上好问候，你提出开始 PAIV Lite 项目\n- 现在：08:16，准备开工\n\n---\n\n这样我可以基于正确的上下文继续今天的工作，而不是从头猜 😅' }
    ]
  }
]

export default function PromptConverter() {
  const [inputMethod, setInputMethod] = useState('sample') // 'sample' | 'manual'
  const [selectedDialogue, setSelectedDialogue] = useState(SAMPLE_DIALOGUES[0])
  const [manualInput, setManualInput] = useState('')
  const [assistantName, setAssistantName] = useState('太古龙67')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const [error, setError] = useState(null)

  const handleConvert = async () => {
    setLoading(true)
    setError(null)
    
    try {
      const dialogues = inputMethod === 'sample' 
        ? SAMPLE_DIALOGUES 
        : parseManualInput(manualInput)
      
      const response = await axios.post(`${API_URL}/api/convert`, {
        dialogues,
        assistantName
      })
      
      setResult(response.data)
    } catch (err) {
      setError(err.response?.data?.error || err.message)
      // 如果 API 不可用，使用本地转换逻辑
      handleLocalConvert()
    } finally {
      setLoading(false)
    }
  }

  const handleLocalConvert = () => {
    // 本地备用转换逻辑
    const dialogues = inputMethod === 'sample' 
      ? SAMPLE_DIALOGUES 
      : parseManualInput(manualInput)
    
    const features = extractFeatures(dialogues)
    const systemPrompt = generateLocalPrompt(features, assistantName)
    
    setResult({
      success: true,
      systemPrompt,
      features
    })
  }

  const parseManualInput = (text) => {
    // 简单解析用户粘贴的对话
    return [{
      id: 'manual-1',
      title: '用户输入对话',
      messages: [{ role: 'user', content: text }, { role: 'assistant', content: '...' }]
    }]
  }

  const extractFeatures = (dialogues) => {
    const features = {
      tone: [],
      communicationStyle: [],
      expertise: []
    }
    
    // 简单的特征提取逻辑
    const allContent = dialogues.flatMap(d => 
      d.messages.filter(m => m.role === 'assistant').map(m => m.content)
    ).join(' ')
    
    if (allContent.includes('🚀') || allContent.includes('✅') || allContent.includes('☀️')) {
      features.tone.push('enthusiastic')
    }
    if (allContent.includes('📋') || allContent.includes('📊') || allContent.includes('表格')) {
      features.communicationStyle.push('visual')
      features.communicationStyle.push('structured')
    }
    if (allContent.includes('```') || allContent.includes('API') || allContent.includes('代码')) {
      features.communicationStyle.push('technical')
    }
    if (allContent.includes('项目') || allContent.includes('架构') || allContent.includes('协议')) {
      features.expertise.push('product_management')
      features.expertise.push('system_design')
    }
    
    return features
  }

  const generateLocalPrompt = (features, name) => {
    return `# System Prompt for ${name}

## 身份定位
你是 ${name}，一个基于 PAIV Protocol 的个人 AI 助手。

## 核心特征
- **语调风格**：${features.tone.includes('enthusiastic') ? '充满活力，使用表情符号' : '专业、友好'}
- **沟通方式**：${features.communicationStyle.includes('structured') ? '结构化呈现，善用表格和列表' : '清晰、有条理'}
- **专业领域**：${features.expertise.join('、') || '通用领域'}

## 行为准则
1. 保持对话的连贯性和上下文理解
2. 主动提供结构化、可操作的建议
3. 在适当时候使用表情符号增强表达（如 🚀 ✅ 📋）
4. 复杂概念用表格、列表或代码块呈现
5. 技术讨论时提供清晰的示例

## 记忆与上下文
- 记住用户的偏好和工作习惯
- 主动关联之前的对话内容
- 在项目讨论中保持术语一致性

## 安全与隐私
- 尊重用户数据主权
- 不泄露敏感信息
- 遵循 PAIV Protocol 的数据迁移原则

---
*Generated by PAIV-Lite v1.0*`
  }

  const handleCopy = () => {
    if (result?.systemPrompt) {
      navigator.clipboard.writeText(result.systemPrompt)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const handleDownload = () => {
    if (result?.systemPrompt) {
      const blob = new Blob([result.systemPrompt], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `system-prompt-${assistantName}.txt`
      a.click()
      URL.revokeObjectURL(url)
    }
  }

  return (
    <div className="converter">
      <div className="converter-header">
        <Sparkles className="icon" />
        <h2>Prompt 转换器</h2>
        <p>从对话样本中提取特征，生成 Gemini/Claude 可用的 System Prompt</p>
      </div>

      <div className="input-section">
        <div className="input-tabs">
          <button 
            className={inputMethod === 'sample' ? 'active' : ''}
            onClick={() => setInputMethod('sample')}
          >
            <FileText size={16} />
            使用示例对话
          </button>
          <button 
            className={inputMethod === 'manual' ? 'active' : ''}
            onClick={() => setInputMethod('manual')}
          >
            <Upload size={16} />
            粘贴对话
          </button>
        </div>

        {inputMethod === 'sample' ? (
          <div className="sample-selector">
            <label>选择对话样本：</label>
            <select 
              value={selectedDialogue.id}
              onChange={(e) => {
                const dialogue = SAMPLE_DIALOGUES.find(d => d.id === e.target.value)
                setSelectedDialogue(dialogue)
              }}
            >
              {SAMPLE_DIALOGUES.map(d => (
                <option key={d.id} value={d.id}>{d.title}</option>
              ))}
            </select>
            
            <div className="preview-box">
              <h4>预览：{selectedDialogue.title}</h4>
              {selectedDialogue.messages.slice(0, 2).map((msg, idx) => (
                <div key={idx} className={`message ${msg.role}`}>
                  <strong>{msg.role === 'user' ? '用户' : 'AI'}:</strong>
                  <p>{msg.content.substring(0, 100)}...</p>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div className="manual-input">
            <textarea
              placeholder="在此粘贴对话内容...\n\n格式示例：\n用户: 你好\nAI: 你好！有什么可以帮你的吗？"
              value={manualInput}
              onChange={(e) => setManualInput(e.target.value)}
              rows={8}
            />
          </div>
        )}

        <div className="options">
          <label>
            助手名称：
            <input 
              type="text" 
              value={assistantName}
              onChange={(e) => setAssistantName(e.target.value)}
              placeholder="例如：太古龙67"
            />
          </label>
        </div>

        <button 
          className="convert-btn"
          onClick={handleConvert}
          disabled={loading}
        >
          {loading ? '转换中...' : '🚀 生成 System Prompt'}
        </button>

        {error && <div className="error">错误: {error}</div>}
      </div>

      {result && (
        <div className="result-section">
          <div className="result-header">
            <h3>生成的 System Prompt</h3>
            <div className="actions">
              <button onClick={handleCopy} className="icon-btn">
                {copied ? <Check size={16} /> : <Copy size={16} />}
                {copied ? '已复制' : '复制'}
              </button>
              <button onClick={handleDownload} className="icon-btn">
                <Download size={16} />
                下载
              </button>
            </div>
          </div>

          {result.features && (
            <div className="features">
              <h4>检测到的特征：</h4>
              <div className="feature-tags">
                {result.features.tone?.map(t => (
                  <span key={t} className="tag tone">语调: {t}</span>
                ))}
                {result.features.communicationStyle?.map(s => (
                  <span key={s} className="tag style">风格: {s}</span>
                ))}
                {result.features.expertise?.map(e => (
                  <span key={e} className="tag expertise">领域: {e}</span>
                ))}
              </div>
            </div>
          )}

          <pre className="prompt-output">{result.systemPrompt}</pre>
        </div>
      )}
    </div>
  )
}
